### ISSUE TITLE
lost connection after CONNECT from localhost[127.0.0.1]

### ISSUE THREAD

**Issue by glennpierce** [loganmarchione/docker-postfixrelay#37]
I have a setup like

```
version: "3"
services:
  postfixrelay:
    container_name: docker-postfixrelay
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - RELAY_HOST=smtp.gmail.com
      - RELAY_PORT=587
      - RELAY_USER=support@carnego.net
      - RELAY_PASS=******
      - FROMADDRESS=support@carnego.net
      - TEST_EMAIL=****@gmail.com
      - MYORIGIN=carnego.net
      - MYNETWORKS=127.0.0.0/24, 192.168.80.0/20, 192.168.22.0/24
      - MSG_SIZE=30720000
    networks:
      - carnego
    ports:
      - 192.168.80.1:8025:25
    image: loganmarchione/docker-postfixrelay:latest
networks:
  carnego:
    external: true
```

network carnego is

"Subnet": "192.168.80.0/20",
"Gateway": "192.168.80.1

The test email gets sent ok when I deploy but when I try to send from the host say from a python script

like 

s = smtplib.SMTP('192.168.80.1', port=8025)

I get 

lost connection after CONNECT from localhost[127.0.0.1]

Any idea why ?

Note I get the same error without mynetworks being set
