### ISSUE TITLE
Logs spammed with lost connection after CONNECT from localhost[127.0.0.1]

### ISSUE THREAD

**Issue by truncsphere** [loganmarchione/docker-postfixrelay#39]
I noticed my logs is getting spammed with the below. Emails are still coming through as expected. Is there a way to track down what is causing this log entry? 

```
May 08 09:30:43 b278eb55986d postfix/smtpd[479]: connect from localhost[127.0.0.1]

May 08 09:30:43 b278eb55986d postfix/smtpd[479]: lost connection after CONNECT from localhost[127.0.0.1]

May 08 09:30:43 b278eb55986d postfix/smtpd[479]: disconnect from localhost[127.0.0.1] commands=0/0
```

```
version: '3'
services:
  postfixrelay:
    container_name: docker-postfixrelay
    restart: unless-stopped
    environment:
      - TZ=America/****
      - RELAY_HOST=smtp.gmail.com
      - RELAY_PORT=587
      - RELAY_USER=email@domain.com
      - RELAY_PASS=SECRET
      - TEST_EMAIL=email@domain.com
      - MYORIGIN=domain.com
      - FROMADDRESS=email@domain.com
      - MSG_SIZE=30720000
    ports:
      - '25:25'
    volumes:
      - 'postfixrelay_data:/var/spool/postfix'
    image: loganmarchione/docker-postfixrelay:latest

volumes:
  postfixrelay_data:
    driver: local
```
