### ISSUE TITLE
Using files for secrets

### ISSUE THREAD

**Issue by r3mi** [loganmarchione/docker-postfixrelay#60]
Hello,
I would like to provide the value of secrets through files, in addition to the current environnement variables.
Then, it would be possible to benefit from [Docker secrets](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images).
For example, instead of directly:
`RELAY_PASS=<some password>`
I would be able to provide:
`RELAY_PASS_FILE=/run/secrets/my_password`
(and other sensitive variables, eg `RELAY_USER` ...)

Is it planned in the roadmap ?

I think it could be something like that in the `entrypoint.sh`:
```
pass="${RELAY_PASS:-$(cat ''$RELAY_PASS_FILE)}"
user="${RELAY_USER:-$(cat ''$RELAY_USER_FILE)}"
...
```

thanks for docker-postfixrelay! very useful.

**Comment by loganmarchione** [comment]
I don't use Docker secrets, but can add this if you can test it.

I see a lot of containers using [this function](https://github.com/docker-library/postgres/blob/729d22b104ede82d7b2d8681bb85f2f44c33eb60/17/bookworm/docker-entrypoint.sh#L5-L25), so I could shamelessly copy it..

```
# usage: file_env VAR [DEFAULT]
#    ie: file_env 'XYZ_DB_PASSWORD' 'example'
# (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of
#  "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
file_env() {
	local var="$1"
	local fileVar="${var}_FILE"
	local def="${2:-}"
	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
		printf >&2 'error: both %s and %s are set (but are exclusive)\n' "$var" "$fileVar"
		exit 1
	fi
	local val="$def"
	if [ "${!var:-}" ]; then
		val="${!var}"
	elif [ "${!fileVar:-}" ]; then
		val="$(< "${!fileVar}")"
	fi
	export "$var"="$val"
	unset "$fileVar"
}
```

**Comment by r3mi** [comment]
thanks. Yes I could test a version.
But would this function works with `sh`, or will require `bash` ?

**Comment by loganmarchione** [comment]
It does require `bash`, nice call.

I just pushed version [`1.5.0`](https://hub.docker.com/layers/loganmarchione/docker-postfixrelay/1.5.0/images/sha256-151739dcfbb4220a16d5dbe96d2e99a623a0ce88a348eac158286a6bcd9bd609) with support for secrets. Can you test? It works on my machine locally, but it would be nice to have someone else verify. There is an updated README with an example too.


```
version: '3'
services:
  postfixrelay:
    container_name: docker-postfixrelay
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - RELAY_HOST=smtp.gmail.com
      - RELAY_PORT=587
      # comment out if using secrets
      - RELAY_USER=your_email_here@gmail.com
      - RELAY_PASS=your_password_here
      # uncomment below if using secrets
      # - RELAY_USER_FILE=/run/secrets/RELAY_USER_FILE
      # - RELAY_PASS_FILE=/run/secrets/RELAY_PASS_FILE
      - RELAY_SUBMISSIONS=true
      - RELAY_SUBMISSIONS=true
      - TEST_EMAIL=test_email@domain.com
      - MYORIGIN=domain.com
      - FROMADDRESS=my_email@domain.com
      - MYNETWORKS=1.2.3.4/24
      - MSG_SIZE=30720000
      - LOG_DISABLE=true
    # uncomment below if using secrets
    # secrets:
    #   - RELAY_USER_FILE
    #   - RELAY_PASS_FILE
    networks:
      - postfixrelay
    ports:
      - '25:25'
    volumes:
      - 'postfixrelay_data:/var/spool/postfix'
    image: loganmarchione/docker-postfixrelay:latest

networks:
  postfixrelay:

volumes:
  postfixrelay_data:
    driver: local

# uncomment below if using secrets
# secrets:
#    RELAY_USER_FILE:
#      file: ./relay_user.txt
#    RELAY_PASS_FILE:
#      file: ./relay_pass.txt
```
